--Создание таблицы "Пользователи"
CREATE TABLE USERS (
    USER_ID INTEGER NOT NULL, 
    LOGIN VARCHAR(50) UNIQUE NOT NULL, 
    PASSWORD VARCHAR(50) NOT NULL,
    USER_STATUS VARCHAR(50) DEFAULT 'not_blocked' ,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT USER_STATUS_TYPE CHECK (
    	USER_STATUS IN ('blocked', 'not_blocked')),
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);

--Создание таблицы "Роли"
CREATE TABLE ROLES (
    USER_ID INTEGER NOT NULL,
    USER_ROLE VARCHAR(50) NOT NULL,
    CONSTRAINT ROLE_TYPE CHECK (
		USER_ROLE IN ('administrator', 'moderator', 'passenger', 'driver')),
    CONSTRAINT ROLE_PK PRIMARY KEY (USER_ID, USER_ROLE),
    CONSTRAINT USER_FK 
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) 
        ON DELETE CASCADE
);

--Создание таблицы "Оценки"
CREATE TABLE MARKS (
    MARK_ID INTEGER NOT NULL,
    FROM_USER INTEGER NOT NULL,
    TO_USER INTEGER NOT NULL,
    TRIP_ID INTEGER NOT NULL,
    MARK INTEGER NOT NULL,
    CONSTRAINT MARK_PK PRIMARY KEY (MARK_ID),
    CONSTRAINT USER_FK1 
        FOREIGN KEY (FROM_USER)
        REFERENCES USERS (USER_ID) 
        ON DELETE CASCADE,
    CONSTRAINT USER_FK2 
        FOREIGN KEY (TO_USER)
        REFERENCES USERS (USER_ID) 
        ON DELETE CASCADE,
    CONSTRAINT TRIP_FK
        FOREIGN KEY (TRIP_ID)
        REFERENCES TRIPS (TRIP_ID) 
        ON DELETE CASCADE
);

--Создание таблицы "Сессии"
CREATE TABLE SESSIONS (
    SESSION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    ACTIVE_UNTIL TIMESTAMP NOT NULL,
    TOKEN VARCHAR(50) NOT NULL,
    CONSTRAINT SESSION_PK PRIMARY KEY (SESSION_ID),
    CONSTRAINT USER_FK3 
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) 
        ON DELETE CASCADE
);

--Создание таблицы "Поездки"
CREATE TABLE TRIPS (
    TRIP_ID INTEGER NOT NULL,
    START_POINT VARCHAR(50) NOT NULL,
    FINAL_POINT VARCHAR(50) NOT NULL,
    TRIP_DATE TIMESTAMP NOT NULL,
    FREE_SEATS INTEGER NOT NULL,
    PRICE FLOAT NOT NULL,
    DRIVER_ID INTEGER NOT NULL,
    TRIP_STATUS VARCHAR(50) DEFAULT 'in_waiting',
    CONSTRAINT TRIP_STATUS_TYPE CHECK (
		TRIP_STATUS IN ('completed', 'not_completed', 'in_waiting')),
    CONSTRAINT TRIP_PK PRIMARY KEY (TRIP_ID),
    CONSTRAINT USER_FK4 
        FOREIGN KEY (DRIVER_ID)
        REFERENCES USERS (USER_ID) 
        ON DELETE CASCADE
);

--Создание таблицы "Заявки"
CREATE TABLE REQUESTS (
    REQUEST_ID INTEGER NOT NULL,
    PASSENGER_ID INTEGER NOT NULL,
    TRIP_ID INTEGER NOT NULL,
    REQUEST_STATUS VARCHAR(50) DEFAULT 'in_waiting',
    CONSTRAINT REQUEST_PK PRIMARY KEY (TRIP_ID),
    CONSTRAINT REQUEST_STATUS_TYPE CHECK (
		REQUEST_STATUS IN ('approved', 'not_approved', 'in_waiting')),
    CONSTRAINT TRIP_FK1 
        FOREIGN KEY (TRIP_ID)
        REFERENCES TRIPS (TRIP_ID) 
        ON DELETE CASCADE,
    CONSTRAINT USER_FK5 
        FOREIGN KEY (PASSENGER_ID)
        REFERENCES USERS (USER_ID) 
        ON DELETE CASCADE
);
